name = "JuliVerse"
uuid = "cc0c3578-aadb-4237-91ce-897ec67b0ab5"
authors = ["Jake krogh"]
version = "1.0.0-DEV"

[compat]
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
